export PULUMI_VERSION='3.117.0'
export PROXMOXVE_PLUGIN_VERSION='6.7.1'
export PULUMI_PROXMOXVE_YAML_DOCKER_IMAGE="${PULUMI_PROXMOXVE_YAML_DOCKER_IMAGE:-pulumi-proxmoxve-yaml}"
export PULUMI_PROXMOXVE_YAML_DOCKER_TAG="${PULUMI_PROXMOXVE_YAML_DOCKER_TAG:-$PULUMI_VERSION-$PROXMOXVE_PLUGIN_VERSION}"
export PULUMI_CONFIG_PASSPHRASE=''